<?php

require_once __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

use PhpMqtt\Client\MqttClient;
use PhpMqtt\Client\ConnectionSettings;

echo "🇨🇲 Real Device Message Simulator for 2581924_ipobexa\n";
echo "====================================================\n\n";

// MQTT Configuration
$host = '172.17.31.181';
$port = 1883;
$username = 'rodadmin';
$password = 'YOUR_MQTT_PASSWORD';
$deviceId = '2581924_ipobexa';

// Test messages in your device format (4 types as per documentation)
$testMessages = [
    // 1. Normal personnel identification record
    [
        'PersonnelId' => '1',  // Maps to student ID 1 (Isaac Biya)
        'VerifyStatus' => 1,   // Normal successful identification
        'Timestamp' => now()->toISOString(),
        'MessageId' => 'msg_normal_' . uniqid(),
        'DeviceId' => $deviceId,
        'Type' => 'Normal Identification'
    ],
    // 2. Control records generated by remote door opening commands
    [
        'PersonnelId' => '1',
        'VerifyStatus' => 3,   // Assuming 3 is for remote door opening
        'Timestamp' => now()->addSeconds(5)->toISOString(),
        'MessageId' => 'msg_remote_' . uniqid(),
        'DeviceId' => $deviceId,
        'Type' => 'Remote Door Opening',
        'Command' => 'OPEN_DOOR'
    ],
    // 3. Unauthorised access record ("VerifyStatus":24)
    [
        'PersonnelId' => '9999',
        'VerifyStatus' => 24,  // Unauthorized access
        'Timestamp' => now()->addSeconds(10)->toISOString(),
        'MessageId' => 'msg_unauthorized_' . uniqid(),
        'DeviceId' => $deviceId,
        'Type' => 'Unauthorized Access'
    ],
    // 4. Blacklist Denial of Access Record ("VerifyStatus":2)
    [
        'PersonnelId' => '8888',
        'VerifyStatus' => 2,   // Blacklist denial
        'Timestamp' => now()->addSeconds(15)->toISOString(),
        'MessageId' => 'msg_blacklist_' . uniqid(),
        'DeviceId' => $deviceId,
        'Type' => 'Blacklist Denial'
    ]
];

try {
    // Create MQTT client
    $clientId = 'device-simulator-' . uniqid();
    $connectionSettings = (new ConnectionSettings())
        ->setUsername($username)
        ->setPassword($password)
        ->setKeepAliveInterval(60);

    $client = new MqttClient($host, $port, $clientId);
    
    echo "🔗 Connecting to MQTT broker...\n";
    $client->connect($connectionSettings, true);
    echo "✅ Connected successfully!\n\n";

    // Publish test messages
    $topic = "mqtt/face/{$deviceId}/Rec";
    
    foreach ($testMessages as $index => $message) {
        $messageJson = json_encode($message);
        $messageType = $message['Type'];
        
        echo "📤 Sending message " . ($index + 1) . " - {$messageType}:\n";
        echo "   Topic: {$topic}\n";
        echo "   PersonnelId: {$message['PersonnelId']}\n";
        echo "   VerifyStatus: {$message['VerifyStatus']}\n";
        echo "   MessageId: {$message['MessageId']}\n";
        echo "   Message: {$messageJson}\n";
        
        $client->publish($topic, $messageJson, 1);
        echo "   ✅ Message sent!\n";
        echo "   ⏳ Waiting for acknowledgment from Laravel...\n\n";
        
        sleep(3); // Wait between messages to see replies
    }

    $client->disconnect();
    echo "🎉 All test messages sent successfully!\n";
    echo "\nNext steps:\n";
    echo "1. Start MQTT subscriber: php artisan mqtt:subscribe\n";
    echo "2. Check logs: php check_logs.php\n";

} catch (Exception $e) {
    echo "❌ Error: " . $e->getMessage() . "\n";
}